# Uncomment the next line to define a global platform for your project
platform :osx, '10.7'

target 'Swift_Speech_Recognition' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift_Speech_Recognition

pod 'InstantSearchVoiceOverlay', '~> 1.1.0'


end
